# Generated by Django 5.2.15 on 2026-06-15 18:25

from django.db import migrations, models


def seed_diplomas(apps, schema_editor):
    """Populate diplomas from each specialist's real credentials
    (education degrees + therapeutic approaches), deduped, max 5."""
    Specialist = apps.get_model("catalog", "Specialist")
    for sp in Specialist.objects.all():
        items = [e.degree for e in sp.education.all()] + list(sp.approaches or [])
        seen = []
        for it in items:
            if it and it not in seen:
                seen.append(it)
        sp.diplomas = seen[:5]
        sp.save(update_fields=["diplomas"])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_seed_specialists'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialist',
            name='diplomas',
            field=models.JSONField(blank=True, default=list, help_text='Названия дипломов и сертификатов'),
        ),
        migrations.RunPython(seed_diplomas, noop),
    ]
