# Generated by Django 5.2.15 on 2026-06-16 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_specialist_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialist',
            name='availability',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
