# Generated by Django 5.2.15 on 2026-06-20 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_specialist_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialist',
            name='accepts_instant',
            field=models.BooleanField(default=False, help_text='Готов(а) к мгновенным сессиям «поговорить сейчас»'),
        ),
        migrations.AddField(
            model_name='specialist',
            name='instant_until',
            field=models.DateTimeField(blank=True, help_text='До какого момента действует статус «доступен сейчас»', null=True),
        ),
    ]
