# Generated by Django 5.2.15 on 2026-06-16 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='call_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conversation',
            name='call_requested',
            field=models.BooleanField(default=False),
        ),
    ]
