# Generated by Django 5.2.15 on 2026-06-15 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_seed_specialists'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField()),
                ('format', models.CharField(choices=[('video', 'Видео'), ('audio', 'Аудио'), ('chat', 'Чат')], default='video', max_length=10)),
                ('duration_minutes', models.PositiveIntegerField(default=50)),
                ('price_kzt', models.PositiveIntegerField(default=0)),
                ('service_fee_kzt', models.PositiveIntegerField(default=1000)),
                ('status', models.CharField(choices=[('pending_payment', 'Ожидает оплаты'), ('paid', 'Оплачено'), ('completed', 'Завершено'), ('cancelled', 'Отменено'), ('refunded', 'Возврат')], default='pending_payment', max_length=20)),
                ('payment_provider', models.CharField(blank=True, default='', max_length=40)),
                ('payment_id', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='catalog.specialist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сессия (бронь)',
                'verbose_name_plural': 'Сессии (брони)',
                'ordering': ['-starts_at'],
            },
        ),
    ]
