# Generated by Django 5.2.15 on 2026-06-16 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
        ('catalog', '0005_specialist_availability'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='client_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='booking',
            name='concern',
            field=models.CharField(blank=True, default='', help_text='Что беспокоит (Тревога, Отношения…)', max_length=80),
        ),
        migrations.AddField(
            model_name='booking',
            name='decline_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='booking',
            name='intent',
            field=models.CharField(choices=[('intro', 'Ознакомительная сессия'), ('package', 'Пакет сессий')], default='intro', help_text='Хочет ознакомительную сессию или пакет', max_length=12),
        ),
        migrations.AddField(
            model_name='booking',
            name='is_intro',
            field=models.BooleanField(default=False, help_text='Бесплатная ознакомительная сессия'),
        ),
        migrations.AddField(
            model_name='booking',
            name='match_score',
            field=models.PositiveSmallIntegerField(default=0, help_text='% совпадения по подбору (0–100)'),
        ),
        migrations.AddField(
            model_name='booking',
            name='proposed_starts_at',
            field=models.DateTimeField(blank=True, help_text='Психолог предложил другое время', null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('requested', 'Запрос (ждёт подтверждения)'), ('pending_payment', 'Подтверждён — ждёт оплаты'), ('scheduled', 'В расписании'), ('paid', 'Оплачено'), ('completed', 'Завершено'), ('declined', 'Отклонено'), ('cancelled', 'Отменено'), ('refunded', 'Возврат')], default='requested', max_length=20),
        ),
        migrations.CreateModel(
            name='ClientNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_about_me', to=settings.AUTH_USER_MODEL)),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_notes', to='catalog.specialist')),
            ],
            options={
                'verbose_name': 'Заметка о клиенте',
                'verbose_name_plural': 'Заметки о клиентах',
                'constraints': [models.UniqueConstraint(fields=('specialist', 'client'), name='uniq_specialist_client_note')],
            },
        ),
    ]
