# Generated by Django 5.2.15 on 2026-06-20 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_client_message_booking_concern_and_more'),
        ('catalog', '0006_specialist_accepts_instant_specialist_instant_until'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_promo',
            field=models.BooleanField(default=False, help_text='Промо/бесплатная мгновенная сессия — не основа для комиссии'),
        ),
        migrations.AddField(
            model_name='booking',
            name='source',
            field=models.CharField(choices=[('manual', 'Обычная бронь'), ('instant', 'Поговорить сейчас'), ('quiz', 'Из квиза')], default='manual', help_text='Откуда пришла бронь (для аналитики)', max_length=10),
        ),
        migrations.CreateModel(
            name='InstantRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concern', models.CharField(blank=True, default='', max_length=80)),
                ('channel', models.CharField(choices=[('video', 'Видео'), ('audio', 'Аудио'), ('chat', 'Чат')], default='video', max_length=10)),
                ('status', models.CharField(choices=[('waiting', 'Ждёт психолога'), ('claimed', 'Психолог принял'), ('expired', 'Истекла'), ('cancelled', 'Отменена')], default='waiting', max_length=12)),
                ('respond_within_min', models.PositiveSmallIntegerField(default=15, help_text='Обещанное время отклика, мин (из настроек)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instant_request', to='booking.booking')),
                ('specialist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instant_requests', to='catalog.specialist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instant_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Заявка «поговорить сейчас»',
                'verbose_name_plural': 'Заявки «поговорить сейчас»',
                'ordering': ['-created_at'],
            },
        ),
    ]
