# Generated by Django 5.2.15 on 2026-06-20 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_whom', models.CharField(blank=True, help_text='Кому ищут помощь: self / relative / child', max_length=20)),
                ('topics', models.JSONField(blank=True, default=list, help_text='Что беспокоит (теги)')),
                ('severity', models.CharField(blank=True, help_text='Острота: mild / moderate / severe', max_length=20)),
                ('goal', models.CharField(blank=True, max_length=80)),
                ('format', models.CharField(blank=True, help_text='online / offline', max_length=20)),
                ('language', models.CharField(blank=True, max_length=8)),
                ('urgency', models.CharField(blank=True, max_length=20)),
                ('budget', models.CharField(blank=True, max_length=20)),
                ('contact', models.CharField(blank=True, help_text='Телефон / email / @handle, если оставлен', max_length=120)),
                ('consent', models.BooleanField(default=False, help_text='Согласие на обработку данных (№94-V) на момент отправки')),
                ('matched_ids', models.JSONField(blank=True, default=list, help_text='ID показанных специалистов')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('linked_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Лид',
                'verbose_name_plural': 'Лиды',
                'ordering': ['-created_at'],
            },
        ),
    ]
